// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobilyaMagazasi_Crud_MVC.Data;

#nullable disable

namespace MobilyaMagazasi_Crud_MVC.Migrations
{
    [DbContext(typeof(MobilyaDbContext))]
    [Migration("20230814194656_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MobilyaMagazasi_Crud_MVC.Data.Mobilya", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mobilyalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kanepe",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "Koltuk",
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sandalye",
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tv Ünitesi",
                            Stock = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
